### ISSUE TITLE
Update ng-packagr

### ISSUE THREAD

**Issue by FabianMeul** [tom-odb/angular_builders#4]
Is it possible to update `@angular-devkit/build-ng-packagr` to the latest version?

https://github.com/ng-packagr/ng-packagr/releases/tag/v9.0.0 adds support for copying `assets`, which I need in a project.

https://www.npmjs.com/package/@angular-devkit/build-ng-packagr (v0.900.6) implements ng-packagr 9.0.0.

**Comment by tom-odb** [comment]
Fwiw: this is fixed now
